### ISSUE TITLE
Loading an External API fails

### ISSUE THREAD

**Issue by jephjohnson** [dixieio/redux-json-api#113]
Pardon my lack of knowledge here. When I try to pull in an api from an external source I receive this error. 

Fetch API cannot load https://gist.githubusercontent.com/jephjohnson/7c0a55924dc77f61e061d13cc6c29f97/raw/299648e4c1d615980a43e160ccf8483954d297b2/posts.json. Response to preflight request doesn't pass access control check: A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:8080' is therefore not allowed access.

My endpoints in React:

store.dispatch(setEndpointHost('https://gist.githubusercontent.com/'));
store.dispatch(setEndpointPath('jephjohnson/7c0a55924dc77f61e061d13cc6c29f97/raw/299648e4c1d615980a43e160ccf8483954d297b2'))

class PostList extends React.Component {
    componentWillMount() {
        store.dispatch(readEndpoint('posts.json'));
    }

......

The URL in the console returns all the data as normal:
https://gist.githubusercontent.com/jephjohnson/7c0a55924dc77f61e061d13cc6c29f97/raw/299648e4c1d615980a43e160ccf8483954d297b2/posts.json

Thanks for looking

**Comment by Nopzen** [comment]
Hello @jephjohnson 

Thanks for reaching out, I think your first issue of concern here is to establish a way where you allow your localhost server to gain access to gist.githubusercontent.com, which I'm not sure how you can grant access to that, this is the first issue.

Another thing i would try when you gain access is to `dispatch` the `readEndpoint`with no endpoint, this should create a path that would look like this: https://gist.githubusercontent.com/jephjohnson/7c0a55924dc77f61e061d13cc6c29f97/raw/299648e4c1d615980a43e160ccf8483954d297b2

This will will also return your posts, because the `readEndpoint(arg)` does the following before creating the fetch call:

1. Concat `API_HOST` + `API_PATH` + `ARGUMENT` from the dispatched action.
2. Then attempt to call the path.

I think you would not need the `posts.json` I might be wrong. But first off it seems there is no access allowed from GitHub for you to create a request from another domain.

**Comment by jephjohnson** [comment]
@Nopzen  - Thank you, I'll give that a go
