### ISSUE TITLE
[Caching question] Is the library or redux using some sort of caching?

### ISSUE THREAD

**Issue by gazpachu** [dixieio/redux-json-api#114]
My team and I were experiencing an error randomly. It happens only in some machines. The data comes from the API correctly and gets set into Redux correctly, but in the final render, the content of a specific field called 'summary' disappears 🐙 

We also made sure that the issue is not related with the markup inside `summary`. It has something to do with caching because when we clear the cache in those machines that had the problem, it works fine.

See the field called 'summary' here:

![screen shot 2017-01-18 at 12 40 01](https://cloud.githubusercontent.com/assets/1721288/22066911/575e7a0c-dd8f-11e6-9726-dc018d886de6.png)

**Comment by egeriis** [comment]
Nothing is cached by `redux-json-api`. What it sounds like, is that an object in state is being mutated. Shouldn't be a bug in this lib, but obviously all software has bugs, so I cannot deny it outright :)

**Comment by Nopzen** [comment]
Hi @gazpachu 

You are working with JS objects here, and from what I can see in your summary, the field contains the sign *"* double quotes in the markup, try change this to *'* single quotes, not sure but that could break your code for sure. :)

Since your are stating your value with a doubblequote and then inserting one though the class=" then the code thinks it stops here.

This is all just my initial thoughts but try it out and then see what happens.

**Comment by gazpachu** [comment]
@Nopzen it's not the markup. So far, I think it could be two different endpoints mutating the same resource. I've refactored it to perform the API read operations sequentially and seems to be working well (at least in staging). In production with cache we still have issues.

I will close this issue until I have more details of what's exactly the problem.
