### ISSUE TITLE
[Question] Force the update of the state even when the returned resource is empty

### ISSUE THREAD

**Issue by gazpachu** [dixieio/redux-json-api#120]
I've noticed that, when reading and endpoint, if the returned resource data is an empty array, the state is not updated in redux. This is an issue for me, as my default value for that resource is `null` and I'm expecting it to become an empty array (once the data is loaded from the API), but it never changes. It only changes if the returned resource data is not empty.

<img width="345" alt="screen shot 2017-02-23 at 17 20 56" src="https://cloud.githubusercontent.com/assets/1721288/23267922/79a04220-f9ec-11e6-90b0-340a51bda018.png">

In the screenshot, you can see the default state of the `opportunities` resource. While the value is `null`, I display a loading spinner. Once the data is loaded from the API, I show a message if the array is empty or render the items if it's not.

How can I force the update of the `opportunities` resource in my redux state even if the response from the API is an empty array?

**Comment by Nopzen** [comment]
I think this is pretty intentional from our side of things.

There is no reason to update the redux state if not need be, to me this seem more like a implementation specific detail in your application if you expect a empty array? Then may I suggest just having a empty array as the default instead of `null.`

if the issue is because you are showing a loader mean while its `null` this could maybe listen to `array.isEmpty`?

I hope this is satisfying enough for you, if not I will look into this a bit more, but it just seems to me a bit application specific details this :)

**Comment by gazpachu** [comment]
Thanks @Nopzen,

But I need to catch the 3 states of the resource: when it's null, when it's empty and when it has data:

```
if (this.props.API_resource.data === null) {
    results = <div className="loader-small"></div>; // Show a loading spinner
} else if (this.props.API_resource.data.length === 0) {
    results = <div className="no-data">Data from API is empty</div>;
} else {
    results = 'Render the stuff from the API...'
```

**Comment by Nopzen** [comment]
Hi @gazpachu 

I see what you need here, but like i said this is very implemtation specfic and is not something the `redux-json-api` should solve for you, but i will give you a few hints how you could solve this issue.

Since all the api's are returning a promise you are able to chain these promises and do either

```js
fetchData() {
  dispatch(readEndpoint('your/path/to/endpoint)).then(response => {
    // Dispatch a local action that tells your component that no data is here
  })
}
```

This is more your responsibility todo since we dont want to pollute the state with keys and empty arrays. I think that would be the more appropriate way to deal with this, its also the way that we deal with this our selfs at Dixie.

**Comment by gazpachu** [comment]
Thanks @Nopzen. I'll do that.
