### ISSUE TITLE
add option to automatically paginate readEndpoint

### ISSUE THREAD

**Issue by morenoh149** [dixieio/redux-json-api#126]
Sometimes there is a desire to request all resources of some type. `readEndpoint` can accept an extra option `all = true` which will make this library detect for any `next` key and automatically issue another http request for the next page of results.
This is a convenience and would make the library more declarative to use.

**Comment by Nopzen** [comment]
Hi @morenoh149 

Sorry for the delayed reply, is there a reason why your API dont just support this as a query param such as `https://mysite.io/api/articles?page=all`, then this would be a non issue? and you would limit the amount of http requests made, and giving your users the data faster? because you dont need to do several round trips?

**Comment by egeriis** [comment]
Sounds like an API implementation issue, not so much the client-side implementation.
