### ISSUE TITLE
API_READ fumbles many to many releationships

### ISSUE THREAD

**Issue by Nopzen** [dixieio/redux-json-api#26]
When a endpoint returns a included data set, the reducer should set the relationship in relationships as an array not and object, with only one relation.

Case: (example call: `/api/users?include=comments`).
```javascript
//Backend returns
data: [{
  type: 'users',
  id: 1,
  attributes: {
    name: "Nopzen"
  }
}],
include: [{
  type: 'comment'
  id: 1,
  attributes: {
    text: 'Hello World'
  },
  relationship: {
    user: {
      data: {
        id: 1,
        type: 'users'
      }
    }
}, {
  type: 'comment'
  id: 2,
  attributes: {
    text: 'Goodbye World'
  },
  relationship: {
    user: {
      data: {
        id: 1,
        type: 'users'
      }
    }
}]
```

After it has been reduced i would come out like this
```javascript
users: {
 data: [{
    type: 'users',
    id: 1,
    attributes: {
      name: "Nopzen"
    }, 
    relationships: {
      comments: {
        id: 1,
        type: 'comment'
      }
    }
  }]
}
```
Instead of relationships being and `array` with both comments in, the reducer turns it to and object with one relation.

**Comment by egeriis** [comment]
Good catch. Let's look at this soon.

**Comment by Nopzen** [comment]
This does also cause an issue if using `updateEntity` if you have the writing rights to write this relationship then could potentially clear the entire relations, for given key.

**Comment by matiaszanolli** [comment]
I've been tracing this error since a couple of days, and it seems there's an issue on the function `updateReverseRelationship`.

Let's take a simple example where a user has a list of projects, and each of them has this user as a related entity (it's a one-to-many relationship but it behaves the same way).

As a first step, the state will be filled with the user, its attributes and a list of related projects. For each of them it will call to `updateReverseRelationship`, in order to relate it to the project in case the response doesn't have such a relation. 

This is done by looking for entities related to the project, and as it finds the user (at this point there's a circular reference) it replaces the list of related projects with the single project. This happens on each iteration of the project list and it always ends set as the last processed item.

I made a quick workaround and raised a pull request, it seems to solve this issue and doesn't seem to break any functionality, though it would be good to rethink this logic when it's possible.

**Comment by Nopzen** [comment]
Hey @matiaszanolli.
Ill have a look at the request, soon (highly likely some here mid week next week), a quick workaround might be the solution for now if we dont find a better solution.

I would say that this is kinda a important feature, that it could easily be come a case a item have an one-to-many / many-to-many relation. So i think it would be important to solve this prober from the get go :)

But thanks alot for the quick solution and findings ill revise it next week.
