### ISSUE TITLE
Sorting, filtering & so on

### ISSUE THREAD

**Issue by asiniy** [dixieio/redux-json-api#40]
[JSON API](http://jsonapi.org/) supports a lot of things for fetching data, like sorting, filtering and so on: http://jsonapi.org/format/#fetching-sorting

How can I do same thing with `redux-json-api`?

**Comment by egeriis** [comment]
To some degree. `readEndpoint` accept any URL, including any GET param, like `include`, `filter` or `sort`. 

There's one caveat, however. That is that _redux-json-api_ will not guarantee that the objects are placed in state in the correct order. In the applications we've build at Dixie, we are putting the responsibility of sorting in the client. In rare occasions where we're using pagination, we're also requesting objects in the same order as we're putting them in the client. 

A workaround could be to read from the response object and index the order of resource identifiers, and store them in a state which is specific for the relevant view.

**Comment by Nopzen** [comment]
I do like the idea of sorting and filtering your data, and its fore sure some thing i've been thinking about a few times already, you are not alone @asiniy :)

I think i like the idea of calling the `readEndpoint('/endpoint?sort=age')`, the issue i can see here is there is no way of setting a Ascending or Descending order? Then we are kinda forced into restricting the users with the way that we thing would be the way. And that dosent seem nice to a user that wants `asc` and we are maybe enforcing `dec` - this would then prompt the user to do some sorting anyway in the frontend.

@egeriis - you are mentioning we cant ensure the order of the array? if we order the array in the read returns this new sorted array to be reduced i would assume this is sorted and we can there for ensure the order?

Another thought to take away a readEndpoint with a sort parameter is that when the user then wants to lets say filter something, we are then deleting whats already in the state, and replacing it with a new data set? so we are doing multiple request for a data set we already have ?

**Comment by egeriis** [comment]
_redux-json-api_ does not guarantee a certain order of the objects placed in it's Redux state. This is due to the way it handles additions of new objects and updates to existing objects. A minimal example is this array of `users` objects:

```json
[
  { "id": 1, "type": "users", "attributes": { "name": "Joe" } },
  { "id": 2, "type": "users", "attributes": { "name": "Jane" } }
]
```

If Joe changes his name, and we want to register this update, we would run this code:

```js
dispatch(updateEntity({ "id": 1, "type": "users", "attributes": { "name": "John" } }));
```

What happens when the following PATCH call was successful is that the old object, where _users#1_'s name is "Joe", is removed from state, leaving this state:

```json
[
  { "id": 2, "type": "users", "attributes": { "name": "Jane" } }
]
```

Immediately following is the addition of _users#1_ with the new name, John. And this will simply be pushed to the end of the collection of objects, leading to this state:

```json
[
  { "id": 2, "type": "users", "attributes": { "name": "Jane" } },
  { "id": 1, "type": "users", "attributes": { "name": "John" } }
]
```

So while the initial order had _users#1_ as the first item, it is now the last.

_redux-json-api_ does not concern itself with this, as the order in which an application would like to present these objects may be different from case to case. In one list the users may be sorted by name, while in another they may be sorted by ID. 
_redux-json-api_ doesn't know about this and I reckon it would add a lot of complexity to cover all cases that would be necessary to cover, in order to support ordering from this library.

**Comment by egeriis** [comment]
@asiniy Did you receive a helpful response? Otherwise just reopen this issue and we'll make sure you're leaving this thread as a happy user 😄

**Comment by rsadyhov** [comment]
Ascending order doesn't work - readEndpoint('/endpoint?sort=-age')

**Comment by egeriis** [comment]
@rsadyhov I'll repeat myself:

> redux-json-api does not guarantee a certain order of the objects placed in it's Redux state
